Models/TestUser.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestCentral.Models
{
    //Extend Default Identity Fields (IdentityUser)

    public class TestUser: IdentityUser
    {   [PersonalData]
        public string FirstName { get; set; }
        [PersonalData]
        public string LastName { get; set; }
        [PersonalData]
        public string SchoolName { get; set; }
        [PersonalData]
        public string Emoji { get; set; }

        public TestUser()
        { 
        }

        public TestUser(string firstName, string lastName, string schoolName, string emoji)
        {
            FirstName = firstName;
            LastName = lastName;
            SchoolName = schoolName;
            Emoji = emoji;
        }

    }
}

Areas/Identity/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using TestCentral.Models;

namespace TestCentral.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly UserManager<TestUser> _userManager;
        private readonly SignInManager<TestUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<TestUser> signInManager, 
            ILogger<LoginModel> logger,
            UserManager<TestUser> userManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl = returnUrl ?? Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

Controllers/TestUserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TestCentral.Data;
using TestCentral.Models;
using TestCentral.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace TestCentral.Controllers
{   [Authorize]
    public class TestUserController : Controller
    {
        private TestUserDbContext context;

        public TestUserController(TestUserDbContext dbContext)
        {
            context = dbContext;
        }

        //Get:  /index/
        public IActionResult Index()
        {
            return View();
        }

        //Add New User

        [HttpGet("/AddTestUser")]
        public IActionResult AddTestUser()
        {
            AddTestUserViewModel addTestUserViewModel = new AddTestUserViewModel();
            return View(addTestUserViewModel);
        }


        [HttpPost]

        public IActionResult ProcessAddTestUserForm(AddTestUserViewModel viewModel)
        {

            if (ModelState.IsValid)
            {
                TestUser theUser = new TestUser
                {
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    SchoolName = viewModel.SchoolName,
                    Emoji = viewModel.Emoji,
                };

                context.Users.Add(theUser);
                context.SaveChanges();
                return Redirect("index/");
            }
            return View(viewModel);
        }
    }
}

Views/TestUser/AddTestUser.cshtml
@model TestCentral.ViewModels.AddTestUserViewModel

<h1>Edit Profile</h1>

<form autocomplete="off" asp-controller="TestUser" asp-action="ProcessAddTestUserForm" method="post">

    <div class="form-group">
        <label>First Name</label>
        <input class="form-control" type="text" name="FirstName" />
        <br />
    </div>

    <div class="form-group">
        <label>Last Name</label>
        <input class="form-control" type="text" name="LastName" />
        <br />
    </div>

    <div class="form-group">
        <label>School Name</label>
        <input class="form-control" type="text" name="SchoolName" />
        <br />
    </div>

    <div class="form-group">
        <label>Emoji</label>
        <select class="form-control" name="Emoji">
            <option value="&#128512">&#128512</option>
            <option value="&#128513">&#128513</option>
            <option value="&#128523">&#128523</option>
            <option value="&#128526">&#128526</option>
            <option value="&#127752">&#127752</option>
            <option value="&#127891">&#127891</option>
            <option value="&#11088">&#11088</option>
            <option value="&#128125">&#128125</option>
            <option value="&#129409">&#129409</option>
            <option value="&#128038">&#128038</option>
            <option value="&#128062">&#128062</option>
            <option value="&#128640">&#128640</option>
            <option value="&#129505">&#129505</option>
        </select>
        <br />
    </div>

    <input type="submit" value="Sign up" />

</form>

Views/TestUser/Index.cshtml
@model TestCentral.Models.TestUser

<h1>Hello!</h1>
  

Views/TestUser/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}