Controllers/TestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestCentral.Data;
using TestCentral.Models;
using TestCentral.ViewModels;

namespace TestCentral.Controllers
{
    public class TestController : Controller
    {
        private TestDBContext context;
        public TestController(TestDBContext dbContext)
        {
            context = dbContext;
        }
        [Authorize]
        public IActionResult Index()
        {
            List<Test> tests = context.Tests.ToList();

            return View(tests);
        }
        [HttpGet]
        public IActionResult Add()
        {
            AddTestViewModel addTestViewModel = new AddTestViewModel();
            return View(addTestViewModel);
        }

        [HttpPost]
        public IActionResult ProcessAddTestForm([FromBody] AddTestViewModel addTestViewModel)
        {
            if (ModelState.IsValid)
            {
                Test newTest = new Test
                {
                    NameOfTest = addTestViewModel.NameOfTest,
                    Description = addTestViewModel.Description,
                    UpdatedAt = DateTime.Now,
                    CreatedAt = DateTime.Now,
            };

                context.Tests.Add(newTest);
                context.SaveChanges();

                foreach (Question question in addTestViewModel.Questions)
                {
                    Question newQuestion = new Question
                    {
                        TestId = newTest.Id,
                        Prompt = question.Prompt,
                        Type = question.Type,
                        Answer = question.Answer,
                        ImgRelatedToPrompt = question.ImgRelatedToPrompt
                    };

                    context.Questions.Add(newQuestion);
                    context.SaveChanges();

                    if (question.Options != null)
                    {

                        foreach (Option option in question.Options)
                        {
                            Option newOption = new Option
                            {
                                QuestionId = newQuestion.Id,
                                Value = option.Value,
                                Label = option.Label
                            };
                            context.Options.Add(newOption);
                            context.SaveChanges();
                        }
                    }

                }
                return Redirect("/Test/Details/" + newTest.Id);
            }
            return View("Add", addTestViewModel);
        }


        [HttpGet]
        [Route("/Test/Details/{testId?}")]
        public IActionResult Details(int testId)
        {

            Test t = context.Tests
                .Where(t => t.Id == testId)
                .Include(t => t.Questions)
                .FirstOrDefault();

            int loopRunTimes = 0;
            foreach (Question q in t.Questions)
            {
                if (q.Type == "Multiple Choice")
                {
                    List<Option> o = context.Options
                        .Where(o => o.QuestionId == q.Id)
                        .ToList();
                    q.Options = o;
                }
                loopRunTimes++;
            }

            return View("Details", t);
        }


        [HttpGet]
        public IActionResult Delete(int testId)
        {
            Test theTest = context.Tests.Find(testId);
            context.Tests.Remove(theTest);
            context.SaveChanges();

            return Redirect("/Test");
        }

        [HttpGet]
        [Route("/Test/UpdateTest/{testId?}")]
        public IActionResult UpdateTest(int testId)
        {
            Test theTest = context.Tests
                .Include(t => t.Questions)
                    .ThenInclude(q => q.Options)
                .Single(t => t.Id == testId);

            return View(theTest);

        }

        [HttpPost]
        [Route("/Test/UpdateTest/{testId}")]
        public IActionResult UpdateTest(EditTestViewModel editTest, int testId)
        {
            Test test = context.Tests
                .Include(t => t.Questions)
                .ThenInclude(q => q.Options)
                .Single(t => t.Id == testId);

            if (test == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                test.Description = editTest.Description;
                test.NameOfTest = editTest.NameOfTest;
                test.UpdatedAt = DateTime.Now;

                foreach (Question question in editTest.Questions)
                {
                    Question existingQuestion = context.Questions.SingleOrDefault(q => q.Id == question.Id);

                    existingQuestion.Prompt = question.Prompt;
                    existingQuestion.ImgRelatedToPrompt = question.ImgRelatedToPrompt;
                    existingQuestion.Answer = question.Answer;

                    if (question.Options != null)
                    {
                        foreach (Option option in question.Options)
                        {
                            Option existingOption = context.Options.SingleOrDefault(o => o.Id == option.Id);
                            existingOption.Label = option.Label;
                        }
                    }
                }


                context.SaveChanges();
                return Redirect("/Test/Details/" + test.Id);
            }



            return View("/Index");
        }

    }

}

Views/Test/Add.cshtml
@model TestCentral.ViewModels.AddTestViewModel


<h1>Create New Test</h1>
<body>
    <form>
        <div class="form-group">
            <label for="testName">Test Name:</label>
            <input name="name" type="text" id="testName" />
            <span asp-validation-for="NameOfTest"></span>
        </div>
        <div class="form-group">
            <label for="testDescription">Test Description:</label>
            <input type="text" id="testDescription" name="description" />
            <span asp-validation-for="Description"></span>
        </div>
        <h2>Questions</h2>
        <div id="questionsSection">
        </div>
        <div>
            <button class="btn btn-primary" id="createTestFormAddQuestion">Add a Question</button><br>
            <button id="submit">Finish and Save Test</button><br>
            <button id="discard">Discard Test</button>
        </div>
    </form>
</body>

Views/Test/Details.cshtml
@model TestCentral.Models.Test
<link href="~/css/site.css" rel="stylesheet" />
<script src="~/js/TestDetails.js"></script>

@{
    ViewData["Title"] = "Details";
    int questionNum = 1;
    string[] multipleChoice = { "A", "B", "C", "D", "E", "F" };
    int m = 0;
}
<body >
    <div id="printableArea">
        <div class="headerSection">
            <h1>@Model.NameOfTest</h1>
            <br />
            <div id="testDates">
                <h4> Created at: @Model.CreatedAt</h4>
                <br />
                <h4> Updated at: @Model.UpdatedAt</h4>
            </div>
            <div class="nameSpace">
                <h4 id="name"></h4>
            </div>
        </div>
        <br />
        <br />


        @foreach (Question question in Model.Questions)
        {
            <div class="questionType">
                @if (question.Type == "True/False")
                {
                    <h3>True or False? </h3>
                }
                else if (question.Type == "Free Text")
                {
                    <h3>Short answer (2-4 sentences) </h3>
                }
                else
                {
                    <h3>Multiple Choice: Pick the best option. </h3>
                }
                <h4>Question @questionNum: @question.Prompt </h4>
                @{questionNum++;}
                <br />
            </div>


            <div class="questionsPromptArea">
                <div class="imgsForTest">
                    @if (question.ImgRelatedToPrompt != null && Uri.IsWellFormedUriString(question.ImgRelatedToPrompt, UriKind.Absolute))
                    {
                        <img class="imgRelatedToPrompts" src="@question.ImgRelatedToPrompt" alt="Picture for question @(questionNum-1)">
                    }
                </div>

                <div class="questionOptions">
                    @if (question.Options != null)
                    {
                        m = 0;
                        foreach (Option option in question.Options)
                        {  

                            <h6>@multipleChoice[m] : @option.Label</h6>

                            m++;
                        }
                    }
                </div>
            </div>

            <div class="answers">
                <p> Correct Answer: @question.Answer</p>
            </div>
            <br />
        }
        <br /><br /><br />
    </div>
</body>

<div class="buttons">
    <a asp-action="UpdateTest" asp-controller="Test" asp-route-testId="@Model.Id">
        <input class="btn btn-primary" type="button" value="Edit Test">
    </a>

    <button class="btn btn-info" onclick="printableTest()">Student View</button>

    <button class="btn btn-warning" onclick="printableKey()">Key Only</button>

    <button class="btn btn-secondary" onclick="printDiv('printableArea')">Print Test</button>

    <a asp-action="Details" asp-controller="Test" asp-route-testId="@Model.Id">
        <input class="btn btn-success"type="button" value="Refresh" />
    </a>
    
</div>

Views/Test/Index.cshtml
@model List<TestCentral.Models.Test>

@{
    ViewData["Title"] = "Index";
}
<script src="~/js/SortTable.js"></script>
<script src="~/js/searchTable.js"></script>

<h1>Index</h1>
<br />

<input type="text" class="input-group-text" id="myInput" onkeyup="searchTable()" placeholder="Search for Test Name..." style="width: 100%; border: 2px solid; text-align: left;">

<br />

<body class="tableData">
    <table id="sortableTable" class="table table-hover">
        <thead>
            <tr class="testHeader">
                <th>
                    Test Name <i class="fas fa-sort" onclick="sortTable(0)"></i>
                </th>
                <th>
                    Description <i class="fas fa-sort" onclick="sortTable(1)"></i>
                </th>
                <th>
                    Created<i class="fas fa-sort" onclick="sortTable(2)"></i>
                </th>
                <th>
                    Updated <i class="fas fa-sort" onclick="sortTable(3)"></i>
                </th>
                <th>
                    <a asp-action="Add" asp-controller="Test" style="color: darkgreen">Create<i class="fas fa-plus" style="        color: darkgreen;
        cursor: pointer;"></i></a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.NameOfTest
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        @Convert.ToDateTime(item.CreatedAt).ToString("MM-dd-yyyy")
                    </td>
                    <td>
                        @Convert.ToDateTime(item.UpdatedAt).ToString("MM-dd-yyyy")
                    </td>
                    <td class="testOptions">
                        <a asp-action="UpdateTest" asp-controller="Test" asp-route-testId="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-controller="Test" asp-route-testId="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-controller="Test" asp-route-TestId="@item.Id"><i class="fas fa-trash-alt" style="color: red;"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>

Views/Test/UpdateTest.cshtml
@model TestCentral.Models.Test
    <script src="~/js/testDetails.js"></script>

@{
    ViewData["Title"] = "UpdateTest";
    int questionNumber = 1;
    string[] multipleChoice = { "A", "B", "C", "D", "E" };
    int m = 0;
}

<h1>Edit Test</h1>

<h4>@Model.NameOfTest</h4>
<hr />
<body>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="UpdateTest">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="@Model.Id" />
                <div class="form-group">
                    <label asp-for="NameOfTest" class="control-label">Name of Test</label>
                    <input asp-for="NameOfTest" class="form-control" required minlength="3" maxlength="50"/>
                    <span asp-validation-for="NameOfTest" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" required minlength="3" maxlength="50"/>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                @for (int i = 0; i < Model.Questions.Count(); i++)
                {
                    <input type="hidden" asp-for="@Model.Questions[i].Id"/>
                    <div class="form-group" id="qform-@Model.Questions[i].Id">
                        <h6>Question: @questionNumber</h6>
                        @{questionNumber++;}
                        <label asp-for="@Model.Questions[i].Prompt" class="control-label"></label>
                        <input asp-for="@Model.Questions[i].Prompt" class="form-control" />
                        <span asp-validation-for="@Model.Questions[i].Prompt" class="text-danger"></span>
                        <label asp-for="@Model.Questions[i].Answer" class="control-label"></label>
                        <input asp-for="@Model.Questions[i].Answer" class="form-control" required/>
                        <span asp-validation-for="@Model.Questions[i].Answer" class="text-danger"></span>
                        @if (@Model.Questions[i].ImgRelatedToPrompt != null) 
                        {
                            <h6>Picture Sample</h6>
                            <img src="@Model.Questions[i].ImgRelatedToPrompt" class="imgRelatedToPrompts">
                        }
                        <label asp-for="@Model.Questions[i].ImgRelatedToPrompt" class="control-label">Question Image Link</label>
                        <input type="url"asp-for="@Model.Questions[i].ImgRelatedToPrompt" class="form-control" />
                        <span asp-validation-for="@Model.Questions[i].ImgRelatedToPrompt" class="text-danger"></span>

                        @{Question currentQuestion = Model.Questions[i]; }

                        @if (currentQuestion.Options != null)
                        {
                            m = 0;
                            int optionCount = currentQuestion.Options.Count();

                            @for (int k = 0; k < optionCount; k++)
                            {
                                <input type="hidden" asp-for="@Model.Questions[i].Options[k].Id" />
                                <label asp-for="@Model.Questions[i].Options[k].Label" class="control-label">Option @multipleChoice[m]</label>
                                m++;
                                <input asp-for="@Model.Questions[i].Options[k].Label" class="form-control" />
                            }
                        }
                        <br />
                        <button class="btn btn-danger" type="button" onclick="postDeleteQuestion(@Model.Questions[i].Id)" id="deleteButton-@Model.Questions[i].Id">Delete Question</button>
                    </div>
                }
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" asp-action="UpdateTest" asp-controller="Test" asp-route-testId="@Model.Id" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}